#!/usr/bin/env bash
# setup_fund_wallets.sh — Create 3 isolated Kerrigan fund wallet daemons
#
# Creates:
#   /mnt/daemons/kerrigan-founders/     — 5% founders rewards (1 address)
#   /mnt/daemons/kerrigan-devtreasury/  — 15% dev + 40% AI treasury (2 addresses)
#   /mnt/daemons/kerrigan-miner/        — personal mining wallet (1 address)
#
# Outputs real 20-byte pubkey hashes for chainparams.cpp
# Installs systemd units from contrib/init/kerrigand-*.service
#
# Usage: ./contrib/setup_fund_wallets.sh [--force [--yes]]

set -euo pipefail
umask 077  # Restrict all created files to owner-only

# ─── Configuration ───────────────────────────────────────────────────────────

SRCDIR="$(cd "$(dirname "$0")/.." && pwd)"
KERRIGAND="${SRCDIR}/src/kerrigand"
CLI="${SRCDIR}/src/kerrigan-cli"
DAEMON_BASE="/mnt/daemons"
SERVICE_SRC="${SRCDIR}/contrib/init"
OUTPUT_FILE="${DAEMON_BASE}/fund_addresses.txt"

FORCE=false
YES=false
BACKUP_PASSPHRASE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --force) FORCE=true; shift ;;
        --yes)   YES=true; shift ;;
        --backup-passphrase)
            echo "WARNING: --backup-passphrase is deprecated (visible in process list)." >&2
            echo "         Passphrase will be prompted interactively instead." >&2
            shift 2 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

# Daemon definitions: name|p2p_port|rpc_port
DAEMONS=(
    "kerrigan-founders|7120|9998"
    "kerrigan-devtreasury|7130|9988"
    "kerrigan-miner|7140|9978"
)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()   { echo -e "${RED}[FATAL]${NC} $*" >&2; exit 1; }

# ─── Phase 1: Validate ──────────────────────────────────────────────────────

info "Phase 1: Validating environment..."

[[ -x "$KERRIGAND" ]] || die "kerrigand not found at $KERRIGAND — build first"
[[ -x "$CLI" ]]       || die "kerrigan-cli not found at $CLI — build first"

# Check for jq or python3 for JSON parsing
if command -v jq &>/dev/null; then
    JSON_TOOL="jq"
elif command -v python3 &>/dev/null; then
    JSON_TOOL="python3"
else
    die "Neither jq nor python3 found — install one for JSON parsing"
fi
info "Using $JSON_TOOL for JSON parsing"

# Create base dir
sudo mkdir -p "$DAEMON_BASE"
sudo chown "$(whoami):$(whoami)" "$DAEMON_BASE"

# Check existing dirs
for entry in "${DAEMONS[@]}"; do
    IFS='|' read -r name _ _ <<< "$entry"
    datadir="${DAEMON_BASE}/${name}"
    if [[ -d "$datadir" ]]; then
        if $FORCE; then
            rpc_port="$(echo "$entry" | cut -d'|' -f3)"

            # Auto-backup existing wallet descriptors before destruction
            backup_dir="${DAEMON_BASE}/pre-force-backup/$(date +%Y%m%d_%H%M%S)"
            mkdir -p "$backup_dir"
            if "$CLI" -datadir="$datadir" -rpcport="$rpc_port" listdescriptors true > "${backup_dir}/${name}-descriptors.json" 2>/dev/null; then
                chmod 600 "${backup_dir}/${name}-descriptors.json"
                ok "Pre-force backup saved to ${backup_dir}/${name}-descriptors.json"
            else
                warn "Could not backup descriptors for $name (daemon not running?)"
            fi

            # Interactive confirmation unless --yes
            if ! $YES; then
                read -rp "WARNING: Destroy wallet data in ${datadir}? Type YES to confirm: " confirm
                [[ "$confirm" == "YES" ]] || die "Aborted by user"
            fi

            warn "Removing existing $datadir (--force)"
            "$CLI" -datadir="$datadir" -rpcport="$rpc_port" stop 2>/dev/null || true
            sleep 2
            rm -rf "$datadir"
        else
            die "$datadir already exists — use --force to recreate"
        fi
    fi
done

ok "Environment validated"

# ─── Phase 2: Create datadirs + configs ──────────────────────────────────────

info "Phase 2: Creating datadirs and configs..."

# Build addnode list for each daemon (connect to the other two)
get_addnodes() {
    local skip_port="$1"
    local nodes=""
    for entry in "${DAEMONS[@]}"; do
        IFS='|' read -r _ p2p _ <<< "$entry"
        if [[ "$p2p" != "$skip_port" ]]; then
            nodes+="addnode=127.0.0.1:${p2p}"$'\n'
        fi
    done
    echo "$nodes"
}

for entry in "${DAEMONS[@]}"; do
    IFS='|' read -r name p2p_port rpc_port <<< "$entry"
    datadir="${DAEMON_BASE}/${name}"
    conffile="${datadir}/kerrigan.conf"

    mkdir -p "$datadir"

    rpc_pass=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)
    addnodes=$(get_addnodes "$p2p_port")

    cat > "$conffile" <<CONF
# ${name} daemon configuration
# Generated by setup_fund_wallets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

server=1
daemon=0
txindex=1
listen=1

port=${p2p_port}
rpcport=${rpc_port}
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcuser=${name}
rpcpassword=${rpc_pass}

# Connect to sibling daemons
${addnodes}
CONF

    chmod 600 "$conffile"
    ok "Created $conffile (port=${p2p_port}, rpc=${rpc_port})"
done

# ─── Phase 3: Start daemons + generate addresses ────────────────────────────

info "Phase 3: Starting daemons and generating addresses..."

cli_cmd() {
    local name="$1" rpc_port="$2"
    shift 2
    "$CLI" -datadir="${DAEMON_BASE}/${name}" -rpcport="$rpc_port" "$@"
}

wait_for_rpc() {
    local name="$1" rpc_port="$2"
    local max_wait=60 elapsed=0

    while (( elapsed < max_wait )); do
        if cli_cmd "$name" "$rpc_port" getblockchaininfo &>/dev/null; then
            return 0
        fi
        sleep 2
        elapsed=$((elapsed + 2))
    done
    die "Timed out waiting for $name RPC (port $rpc_port) after ${max_wait}s"
}

# Start all daemons
for entry in "${DAEMONS[@]}"; do
    IFS='|' read -r name p2p_port rpc_port <<< "$entry"
    datadir="${DAEMON_BASE}/${name}"

    info "Starting $name..."
    "$KERRIGAND" -datadir="$datadir" -conf="${datadir}/kerrigan.conf" -daemon
done

# Wait for RPC on all
for entry in "${DAEMONS[@]}"; do
    IFS='|' read -r name _ rpc_port <<< "$entry"
    info "Waiting for $name RPC..."
    wait_for_rpc "$name" "$rpc_port"
    ok "$name RPC ready"
done

# Create descriptor wallets (no BDB — legacy wallets not available)
for entry in "${DAEMONS[@]}"; do
    IFS='|' read -r name _ rpc_port <<< "$entry"
    info "Creating wallet on $name..."
    cli_cmd "$name" "$rpc_port" createwallet "main" false false "" false true true >/dev/null
    ok "Wallet created on $name"
done

# Generate addresses
declare -A FUND_ADDRS

# founders: 1 address
FUND_ADDRS[founders]=$(cli_cmd "kerrigan-founders" 9998 getnewaddress "founders")
ok "founders address: ${FUND_ADDRS[founders]}"

# devtreasury: 2 addresses (devfund + aitreasury)
FUND_ADDRS[devfund]=$(cli_cmd "kerrigan-devtreasury" 9988 getnewaddress "devfund")
ok "devfund address: ${FUND_ADDRS[devfund]}"

FUND_ADDRS[aitreasury]=$(cli_cmd "kerrigan-devtreasury" 9988 getnewaddress "aitreasury")
ok "aitreasury address: ${FUND_ADDRS[aitreasury]}"

# miner: 1 address
FUND_ADDRS[mining]=$(cli_cmd "kerrigan-miner" 9978 getnewaddress "mining")
ok "mining address: ${FUND_ADDRS[mining]}"

# ─── Phase 4: Extract 20-byte pubkey hashes ─────────────────────────────────

info "Phase 4: Extracting pubkey hashes..."

extract_pubkeyhash() {
    local name="$1" rpc_port="$2" addr="$3"
    local info_json script_hex hash

    info_json=$(cli_cmd "$name" "$rpc_port" getaddressinfo "$addr")

    if [[ "$JSON_TOOL" == "jq" ]]; then
        script_hex=$(echo "$info_json" | jq -r '.scriptPubKey')
    else
        script_hex=$(echo "$info_json" | python3 -c "import sys,json; print(json.load(sys.stdin)['scriptPubKey'])")
    fi

    # P2PKH: 76a914<20 bytes hex>88ac
    if [[ ${#script_hex} -ne 50 ]]; then
        die "Unexpected scriptPubKey length for $addr: '$script_hex' (expected 50 hex chars for P2PKH)"
    fi
    if [[ "${script_hex:0:6}" != "76a914" ]] || [[ "${script_hex:46:4}" != "88ac" ]]; then
        die "scriptPubKey for $addr is not P2PKH format: $script_hex"
    fi

    hash="${script_hex:6:40}"
    echo "$hash"
}

declare -A FUND_HASHES

FUND_HASHES[founders]=$(extract_pubkeyhash "kerrigan-founders" 9998 "${FUND_ADDRS[founders]}")
ok "founders hash: ${FUND_HASHES[founders]}"

FUND_HASHES[devfund]=$(extract_pubkeyhash "kerrigan-devtreasury" 9988 "${FUND_ADDRS[devfund]}")
ok "devfund hash: ${FUND_HASHES[devfund]}"

FUND_HASHES[aitreasury]=$(extract_pubkeyhash "kerrigan-devtreasury" 9988 "${FUND_ADDRS[aitreasury]}")
ok "aitreasury hash: ${FUND_HASHES[aitreasury]}"

FUND_HASHES[mining]=$(extract_pubkeyhash "kerrigan-miner" 9978 "${FUND_ADDRS[mining]}")
ok "mining hash: ${FUND_HASHES[mining]}"

# ─── Phase 5: Verify ismine ─────────────────────────────────────────────────

info "Phase 5: Verifying ismine for all fund addresses..."

verify_ismine() {
    local name="$1" rpc_port="$2" addr="$3" label="$4"
    local info_json ismine

    info_json=$(cli_cmd "$name" "$rpc_port" getaddressinfo "$addr")

    if [[ "$JSON_TOOL" == "jq" ]]; then
        ismine=$(echo "$info_json" | jq -r '.ismine')
    else
        ismine=$(echo "$info_json" | python3 -c "import sys,json; print(json.load(sys.stdin)['ismine'])")
    fi

    if [[ "$ismine" != "true" ]] && [[ "$ismine" != "True" ]]; then
        die "ismine check FAILED for $label ($addr) on $name"
    fi
    ok "ismine verified: $label ($addr)"
}

verify_ismine "kerrigan-founders"    9998 "${FUND_ADDRS[founders]}"   "founders"
verify_ismine "kerrigan-devtreasury" 9988 "${FUND_ADDRS[devfund]}"    "devfund"
verify_ismine "kerrigan-devtreasury" 9988 "${FUND_ADDRS[aitreasury]}" "aitreasury"
verify_ismine "kerrigan-miner"       9978 "${FUND_ADDRS[mining]}"     "mining"

# ─── Phase 6: Backup private keys ───────────────────────────────────────────

info "Phase 6: Backing up wallet descriptors (encrypted)..."

# Always prompt interactively (never accept passphrase via CLI args — visible in ps)
read -rsp "Enter passphrase for encrypted descriptor backups: " BACKUP_PASSPHRASE
echo
read -rsp "Confirm passphrase: " passphrase_confirm
echo
[[ "$BACKUP_PASSPHRASE" == "$passphrase_confirm" ]] || die "Passphrases do not match"
[[ -n "$BACKUP_PASSPHRASE" ]] || die "Passphrase cannot be empty"

backup_descriptors() {
    local name="$1" rpc_port="$2"
    local datadir="${DAEMON_BASE}/${name}"
    local backup_file="${datadir}/private_key_backup.enc"

    # listdescriptors true exports all descriptors with private keys, encrypted at rest
    # Use env:PASS instead of pass:$PASSPHRASE to avoid exposing in process list
    cli_cmd "$name" "$rpc_port" listdescriptors true | \
        PASS="${BACKUP_PASSPHRASE}" openssl enc -aes-256-cbc -pbkdf2 -salt -out "$backup_file" -pass env:PASS
    chmod 600 "$backup_file"
    ok "Encrypted backup: $name → $backup_file"
}

backup_descriptors "kerrigan-founders"    9998
backup_descriptors "kerrigan-devtreasury" 9988
backup_descriptors "kerrigan-miner"       9978

# ─── Phase 7: Output ────────────────────────────────────────────────────────

info "Phase 7: Summary output..."

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  Kerrigan Fund Wallet Addresses"
echo "═══════════════════════════════════════════════════════════════════"
printf "  %-12s %-36s %s\n" "LABEL" "K-ADDRESS" "PUBKEY HASH (20 bytes)"
echo "───────────────────────────────────────────────────────────────────"
printf "  %-12s %-36s %s\n" "founders"   "${FUND_ADDRS[founders]}"   "${FUND_HASHES[founders]}"
printf "  %-12s %-36s %s\n" "devfund"    "${FUND_ADDRS[devfund]}"    "${FUND_HASHES[devfund]}"
printf "  %-12s %-36s %s\n" "aitreasury" "${FUND_ADDRS[aitreasury]}" "${FUND_HASHES[aitreasury]}"
printf "  %-12s %-36s %s\n" "mining"     "${FUND_ADDRS[mining]}"     "${FUND_HASHES[mining]}"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# C++ ready-to-paste output
CPP_SNIPPET=$(cat <<CPPEOF
// Fund addresses — generated by contrib/setup_fund_wallets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
// founders (5%):      ${FUND_ADDRS[founders]}
// devfund (15%):      ${FUND_ADDRS[devfund]}
// aitreasury (40%):   ${FUND_ADDRS[aitreasury]}
consensus.foundersPaymentScript    = BuildTreasuryScript("${FUND_HASHES[founders]}");
consensus.devFundPaymentScript     = BuildTreasuryScript("${FUND_HASHES[devfund]}");
consensus.aiTreasuryPaymentScript  = BuildTreasuryScript("${FUND_HASHES[aitreasury]}");
CPPEOF
)

echo "Ready-to-paste C++ for chainparams.cpp (all 4 networks):"
echo ""
echo "$CPP_SNIPPET"
echo ""
echo "───────────────────────────────────────────────────────────────────"
echo "  Disaster Recovery: Decrypt wallet backups with:"
echo "    openssl enc -d -aes-256-cbc -pbkdf2 -in <datadir>/private_key_backup.enc"
echo "───────────────────────────────────────────────────────────────────"
echo ""

# Save to file
{
    echo "# Kerrigan Fund Wallet Addresses"
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    echo "founders_addr=${FUND_ADDRS[founders]}"
    echo "founders_hash=${FUND_HASHES[founders]}"
    echo ""
    echo "devfund_addr=${FUND_ADDRS[devfund]}"
    echo "devfund_hash=${FUND_HASHES[devfund]}"
    echo ""
    echo "aitreasury_addr=${FUND_ADDRS[aitreasury]}"
    echo "aitreasury_hash=${FUND_HASHES[aitreasury]}"
    echo ""
    echo "mining_addr=${FUND_ADDRS[mining]}"
    echo "mining_hash=${FUND_HASHES[mining]}"
    echo ""
    echo "# C++ snippet for chainparams.cpp:"
    echo "$CPP_SNIPPET"
} > "$OUTPUT_FILE"
chmod 600 "$OUTPUT_FILE"
ok "Saved to $OUTPUT_FILE"

# ─── Phase 8: Install systemd ───────────────────────────────────────────────

info "Phase 8: Installing systemd units..."

# Stop manually-started daemons
for entry in "${DAEMONS[@]}"; do
    IFS='|' read -r name _ rpc_port <<< "$entry"
    info "Stopping $name..."
    cli_cmd "$name" "$rpc_port" stop 2>/dev/null || true
done

# Wait for daemons to fully stop
info "Waiting for daemons to stop..."
sleep 5

# Copy unit files
for svc in kerrigand-founders kerrigand-devtreasury kerrigand-miner; do
    src="${SERVICE_SRC}/${svc}.service"
    if [[ ! -f "$src" ]]; then
        die "Service file not found: $src"
    fi
    sudo cp "$src" /etc/systemd/system/
    ok "Installed ${svc}.service"
done

# Reload and enable
sudo systemctl daemon-reload
for svc in kerrigand-founders kerrigand-devtreasury kerrigand-miner; do
    sudo systemctl enable --now "${svc}.service"
    ok "Enabled and started ${svc}.service"
done

# Verify
sleep 3
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  Systemd Status"
echo "═══════════════════════════════════════════════════════════════════"
for svc in kerrigand-founders kerrigand-devtreasury kerrigand-miner; do
    status=$(systemctl is-active "${svc}.service" 2>/dev/null || echo "unknown")
    if [[ "$status" == "active" ]]; then
        echo -e "  ${GREEN}●${NC} ${svc}: ${status}"
    else
        echo -e "  ${RED}●${NC} ${svc}: ${status}"
    fi
done
echo "═══════════════════════════════════════════════════════════════════"
echo ""

ok "Setup complete! Run the following after updating chainparams.cpp:"
echo "    cd ${SRCDIR} && make -j\$(nproc)"
echo "    ./src/test/test_kerrigan --run_test=pow_tests"
echo "    ./src/test/test_kerrigan --run_test=coinbase_split_tests"
echo "    ./src/test/test_kerrigan --run_test=subsidy_tests"
