

#include <QtGlobal>

// Automatically generated by extract_strings_qt.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *kerrigan_strings[] = {
QT_TRANSLATE_NOOP("kerrigan", "The %s developers"),
QT_TRANSLATE_NOOP("kerrigan", ""
"%s corrupt. Try using the wallet tool kerrigan-wallet to salvage or restoring a "
"backup."),
QT_TRANSLATE_NOOP("kerrigan", ""
"%s file contains all private keys from this wallet. Do not share it with "
"anyone!"),
QT_TRANSLATE_NOOP("kerrigan", ""
"%s is set very high! Fees this large could be paid on a single transaction."),
QT_TRANSLATE_NOOP("kerrigan", ""
"%s request to listen on port %u. This port is considered \"bad\" and thus it "
"is unlikely that any peer will connect to it. See doc/p2p-bad-ports.md for "
"details and a full list."),
QT_TRANSLATE_NOOP("kerrigan", ""
"%s uses exact denominated amounts to send funds, you might simply need to "
"mix some more coins."),
QT_TRANSLATE_NOOP("kerrigan", ""
"-reindex-chainstate option is not compatible with -blockfilterindex. Please "
"temporarily disable blockfilterindex while using -reindex-chainstate, or "
"replace -reindex-chainstate with -reindex to fully rebuild all indexes."),
QT_TRANSLATE_NOOP("kerrigan", ""
"-reindex-chainstate option is not compatible with -coinstatsindex. Please "
"temporarily disable coinstatsindex while using -reindex-chainstate, or "
"replace -reindex-chainstate with -reindex to fully rebuild all indexes."),
QT_TRANSLATE_NOOP("kerrigan", ""
"-reindex-chainstate option is not compatible with -txindex. Please "
"temporarily disable txindex while using -reindex-chainstate, or replace "
"-reindex-chainstate with -reindex to fully rebuild all indexes."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Cannot downgrade wallet from version %i to version %i. Wallet version "
"unchanged."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Cannot obtain a lock on data directory %s. %s is probably already running."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Cannot provide specific connections and have addrman find outgoing "
"connections at the same time."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Disk space for %s may not accommodate the block files. Approximately %u GB "
"of data will be stored in this directory."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Distributed under the MIT software license, see the accompanying file %s or "
"%s"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Error loading %s: External signer wallet being loaded without external "
"signer support compiled"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Error loading %s: You can't enable HD on an already existing non-HD wallet"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Error loading wallet. Wallet requires blocks to be downloaded, and software "
"does not currently support loading wallets while blocks are being downloaded "
"out of order when using assumeutxo snapshots. Wallet should be able to load "
"successfully after node sync reaches height %s"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Error reading %s! All keys read correctly, but transaction data or address "
"book entries might be missing or incorrect."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Error: Dumpfile format record is incorrect. Got \"%s\", expected \"format\"."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Error: Dumpfile identifier record is incorrect. Got \"%s\", expected \"%s\"."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Error: Dumpfile version is not supported. This version of kerrigan-wallet only "
"supports version 1 dumpfiles. Got dumpfile with version %s"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Failed to create backup, file already exists! This could happen if you "
"restarted wallet in less than 60 seconds. You can continue if you are ok "
"with this."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Failed to rename invalid peers.dat file. Please move or delete it and try "
"again."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Fee estimation failed. Fallbackfee is disabled. Wait a few blocks or enable "
"%s."),
QT_TRANSLATE_NOOP("kerrigan", ""
"File %s already exists. If you are sure this is what you want, move it out "
"of the way first."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Found unconfirmed denominated outputs, will wait till they confirm to "
"continue."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Incompatible options: -dnsseed=1 was explicitly specified, but -onlynet "
"forbids connections to IPv4/IPv6"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Incorrect or no devnet genesis block found. Wrong datadir for devnet "
"specified?"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Invalid -socketevents ('%s') specified. Only these modes are supported: %s"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Invalid amount for %s=<amount>: '%s' (must be at least the minrelay fee of "
"%s to prevent stuck transactions)"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Invalid or corrupt peers.dat (%s). If you believe this is a bug, please "
"report it to %s. As a workaround, you can move the file (%s) out of the way "
"(rename, move, or delete) to have a new one created on the next start."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Make sure to encrypt your wallet and delete all non-encrypted backups after "
"you have verified that the wallet works!"),
QT_TRANSLATE_NOOP("kerrigan", ""
"More than one onion bind address is provided. Using %s for the automatically "
"created Tor onion service."),
QT_TRANSLATE_NOOP("kerrigan", ""
"No dump file provided. To use createfromdump, -dumpfile=<filename> must be "
"provided."),
QT_TRANSLATE_NOOP("kerrigan", ""
"No dump file provided. To use dump, -dumpfile=<filename> must be provided."),
QT_TRANSLATE_NOOP("kerrigan", ""
"No wallet file format provided. To use createfromdump, -format=<format> must "
"be provided."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Outbound connections restricted to CJDNS (-onlynet=cjdns) but "
"-cjdnsreachable is not provided"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Outbound connections restricted to Tor (-onlynet=onion) but the proxy for "
"reaching the Tor network is explicitly forbidden: -onion=0"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Outbound connections restricted to Tor (-onlynet=onion) but the proxy for "
"reaching the Tor network is not provided: none of -proxy, -onion or "
"-listenonion is given"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Outbound connections restricted to i2p (-onlynet=i2p) but -i2psam is not "
"provided"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Please check that your computer's date and time are correct! If your clock "
"is wrong, %s will not work properly."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Please contribute if you find %s useful. Visit %s for further information "
"about the software."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Prune configured below the minimum of %d MiB.  Please use a higher number."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Prune mode is incompatible with -reindex-chainstate. Use full -reindex "
"instead."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Prune: last wallet synchronisation goes beyond pruned data. You need to "
"-reindex (download the whole blockchain again in case of pruned node)"),
QT_TRANSLATE_NOOP("kerrigan", ""
"SQLiteDatabase: Unknown sqlite wallet schema version %d. Only version %d is "
"supported"),
QT_TRANSLATE_NOOP("kerrigan", ""
"The block database contains a block which appears to be from the future. "
"This may be due to your computer's date and time being set incorrectly. Only "
"rebuild the block database if you are sure that your computer's date and "
"time are correct"),
QT_TRANSLATE_NOOP("kerrigan", ""
"The transaction amount is too small to send after the fee has been deducted"),
QT_TRANSLATE_NOOP("kerrigan", ""
"This error could occur if this wallet was not shutdown cleanly and was last "
"loaded using a build with a newer version of Berkeley DB. If so, please use "
"the software that last loaded this wallet"),
QT_TRANSLATE_NOOP("kerrigan", ""
"This is a pre-release test build - use at your own risk - do not use for "
"mining or merchant applications"),
QT_TRANSLATE_NOOP("kerrigan", ""
"This is the maximum transaction fee you pay (in addition to the normal fee) "
"to prioritize partial spend avoidance over regular coin selection."),
QT_TRANSLATE_NOOP("kerrigan", ""
"This is the transaction fee you may discard if change is smaller than dust "
"at this level"),
QT_TRANSLATE_NOOP("kerrigan", ""
"This is the transaction fee you may pay when fee estimates are not available."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Total length of network version string (%i) exceeds maximum length (%i). "
"Reduce the number or size of uacomments."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Transaction requires one destination of non-0 value, a non-0 feerate, or a "
"pre-selected input"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Unable to replay blocks. You will need to rebuild the database using "
"-reindex-chainstate."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Unknown wallet file format \"%s\" provided. Please provide one of \"bdb\" or "
"\"sqlite\"."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Unsupported category-specific logging level -loglevel=%s. Expected "
"-loglevel=<category>:<loglevel>. Valid categories: %s. Valid loglevels: %s."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Unsupported chainstate database format found. Please restart with -reindex-"
"chainstate. This will rebuild the chainstate database."),
QT_TRANSLATE_NOOP("kerrigan", ""
"WARNING! Failed to replenish keypool, please unlock your wallet to do so."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Wallet is locked, can't replenish keypool! Please unlock your wallet to replenish keypool."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Warning: Dumpfile wallet format \"%s\" does not match command line specified "
"format \"%s\"."),
QT_TRANSLATE_NOOP("kerrigan", ""
"Warning: Private keys detected in wallet {%s} with disabled private keys"),
QT_TRANSLATE_NOOP("kerrigan", ""
"Warning: We do not appear to fully agree with our peers! You may need to "
"upgrade, or other nodes may need to upgrade."),
QT_TRANSLATE_NOOP("kerrigan", ""
"You need to rebuild the database using -reindex to enable -timestampindex"),
QT_TRANSLATE_NOOP("kerrigan", ""
"You need to rebuild the database using -reindex to go back to unpruned "
"mode.  This will redownload the entire blockchain"),
QT_TRANSLATE_NOOP("kerrigan", "%s -- Incorrect seed, it should be a hex string"),
QT_TRANSLATE_NOOP("kerrigan", "%s can't be lower than %s"),
QT_TRANSLATE_NOOP("kerrigan", "%s failed"),
QT_TRANSLATE_NOOP("kerrigan", "%s is idle."),
QT_TRANSLATE_NOOP("kerrigan", "%s is not a valid backup folder!"),
QT_TRANSLATE_NOOP("kerrigan", "%s is set very high!"),
QT_TRANSLATE_NOOP("kerrigan", "%s request incomplete:"),
QT_TRANSLATE_NOOP("kerrigan", "-devnet can only be specified once"),
QT_TRANSLATE_NOOP("kerrigan", "-maxmempool must be at least %d MB"),
QT_TRANSLATE_NOOP("kerrigan", "-port must be specified when -devnet and -listen are specified"),
QT_TRANSLATE_NOOP("kerrigan", "-rpcport must be specified when -devnet and -server are specified"),
QT_TRANSLATE_NOOP("kerrigan", "-statsbatchsize cannot be configured with a negative value."),
QT_TRANSLATE_NOOP("kerrigan", "-statsduration cannot be configured with a negative value."),
QT_TRANSLATE_NOOP("kerrigan", "A fatal internal error occurred, see debug.log for details"),
QT_TRANSLATE_NOOP("kerrigan", "Already have that input."),
QT_TRANSLATE_NOOP("kerrigan", "Automatic backups disabled"),
QT_TRANSLATE_NOOP("kerrigan", "Can't find random Masternode."),
QT_TRANSLATE_NOOP("kerrigan", "Can't mix while sync in progress."),
QT_TRANSLATE_NOOP("kerrigan", "Can't mix: no compatible inputs found!"),
QT_TRANSLATE_NOOP("kerrigan", "Cannot create socket (socket() returned error %s)"),
QT_TRANSLATE_NOOP("kerrigan", "Cannot get socket address for %s"),
QT_TRANSLATE_NOOP("kerrigan", "Cannot init Statsd client"),
QT_TRANSLATE_NOOP("kerrigan", "Cannot resolve -%s address: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Cannot set -forcednsseed to true when setting -dnsseed to false."),
QT_TRANSLATE_NOOP("kerrigan", "Cannot set -peerblockfilters without -blockfilterindex."),
QT_TRANSLATE_NOOP("kerrigan", "Cannot write to data directory '%s'; check permissions."),
QT_TRANSLATE_NOOP("kerrigan", "Collateral not valid."),
QT_TRANSLATE_NOOP("kerrigan", "Config setting for %s only applied on %s network when in [%s] section."),
QT_TRANSLATE_NOOP("kerrigan", "Copyright (C)"),
QT_TRANSLATE_NOOP("kerrigan", "Corrupted block database detected"),
QT_TRANSLATE_NOOP("kerrigan", "Could not find asmap file %s"),
QT_TRANSLATE_NOOP("kerrigan", "Could not parse asmap file %s"),
QT_TRANSLATE_NOOP("kerrigan", "Disk space is too low!"),
QT_TRANSLATE_NOOP("kerrigan", "Do you want to rebuild the block database now?"),
QT_TRANSLATE_NOOP("kerrigan", "Done loading"),
QT_TRANSLATE_NOOP("kerrigan", "Dump file %s does not exist."),
QT_TRANSLATE_NOOP("kerrigan", "ERROR! Failed to create automatic backup"),
QT_TRANSLATE_NOOP("kerrigan", "Entries are full."),
QT_TRANSLATE_NOOP("kerrigan", "Entry exceeds maximum size."),
QT_TRANSLATE_NOOP("kerrigan", "Error creating %s"),
QT_TRANSLATE_NOOP("kerrigan", "Error initializing block database"),
QT_TRANSLATE_NOOP("kerrigan", "Error initializing wallet database environment %s!"),
QT_TRANSLATE_NOOP("kerrigan", "Error loading %s"),
QT_TRANSLATE_NOOP("kerrigan", "Error loading %s: Private keys can only be disabled during creation"),
QT_TRANSLATE_NOOP("kerrigan", "Error loading %s: Wallet corrupted"),
QT_TRANSLATE_NOOP("kerrigan", "Error loading %s: Wallet requires newer version of %s"),
QT_TRANSLATE_NOOP("kerrigan", "Error loading %s: You can't disable HD on an already existing HD wallet"),
QT_TRANSLATE_NOOP("kerrigan", "Error loading block database"),
QT_TRANSLATE_NOOP("kerrigan", "Error opening block database"),
QT_TRANSLATE_NOOP("kerrigan", "Error reading from database, shutting down."),
QT_TRANSLATE_NOOP("kerrigan", "Error reading next record from wallet database"),
QT_TRANSLATE_NOOP("kerrigan", "Error upgrading evo database for EHF"),
QT_TRANSLATE_NOOP("kerrigan", "Error: Cannot extract destination from the generated scriptpubkey"),
QT_TRANSLATE_NOOP("kerrigan", "Error: Couldn't create cursor into database"),
QT_TRANSLATE_NOOP("kerrigan", "Error: Disk space is low for %s"),
QT_TRANSLATE_NOOP("kerrigan", "Error: Dumpfile checksum does not match. Computed %s, expected %s"),
QT_TRANSLATE_NOOP("kerrigan", "Error: Got key that was not hex: %s"),
QT_TRANSLATE_NOOP("kerrigan", "Error: Got value that was not hex: %s"),
QT_TRANSLATE_NOOP("kerrigan", "Error: Keypool ran out, please call keypoolrefill first"),
QT_TRANSLATE_NOOP("kerrigan", "Error: Missing checksum"),
QT_TRANSLATE_NOOP("kerrigan", "Error: No addresses available."),
QT_TRANSLATE_NOOP("kerrigan", "Error: Unable to parse version %u as a uint32_t"),
QT_TRANSLATE_NOOP("kerrigan", "Error: Unable to write record to new wallet"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to clear fulfilled requests cache at %s"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to clear governance cache at %s"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to clear masternode cache at %s"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to commit Evo database"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to create backup %s!"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to create backup, error: %s"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to delete backup, error: %s"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to listen on any port. Use -listen=0 if you want this."),
QT_TRANSLATE_NOOP("kerrigan", "Failed to load fulfilled requests cache from %s"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to load governance cache from %s"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to load masternode cache from %s"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to load sporks cache from %s"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to rescan the wallet during initialization"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to upgrade Evo database"),
QT_TRANSLATE_NOOP("kerrigan", "Failed to verify database"),
QT_TRANSLATE_NOOP("kerrigan", "Fee needed > fee paid"),
QT_TRANSLATE_NOOP("kerrigan", "Fee rate (%s) is lower than the minimum fee rate setting (%s)"),
QT_TRANSLATE_NOOP("kerrigan", "Found enough users, signing ( waiting %s )"),
QT_TRANSLATE_NOOP("kerrigan", "Found enough users, signing…"),
QT_TRANSLATE_NOOP("kerrigan", "Host %s on unsupported network"),
QT_TRANSLATE_NOOP("kerrigan", "Ignoring duplicate -wallet %s."),
QT_TRANSLATE_NOOP("kerrigan", "Importing…"),
QT_TRANSLATE_NOOP("kerrigan", "Incompatible mode."),
QT_TRANSLATE_NOOP("kerrigan", "Incompatible version."),
QT_TRANSLATE_NOOP("kerrigan", "Incorrect -rescan mode, falling back to default value"),
QT_TRANSLATE_NOOP("kerrigan", "Incorrect or no genesis block found. Wrong datadir for network?"),
QT_TRANSLATE_NOOP("kerrigan", "Initialization sanity check failed. %s is shutting down."),
QT_TRANSLATE_NOOP("kerrigan", "Input is not valid."),
QT_TRANSLATE_NOOP("kerrigan", "Input not found or already spent"),
QT_TRANSLATE_NOOP("kerrigan", "Inputs vs outputs size mismatch."),
QT_TRANSLATE_NOOP("kerrigan", "Insufficient funds."),
QT_TRANSLATE_NOOP("kerrigan", "Invalid '%s'. Allowed values: 128, 160, 192, 224, 256."),
QT_TRANSLATE_NOOP("kerrigan", "Invalid -i2psam address or hostname: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Invalid -onion address or hostname: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Invalid -proxy address or hostname: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Invalid P2P permission: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Invalid amount for %s=<amount>: '%s' (must be at least %s)"),
QT_TRANSLATE_NOOP("kerrigan", "Invalid amount for %s=<amount>: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Invalid amount for -%s=<amount>: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Invalid masternodeblsprivkey. Please see documentation."),
QT_TRANSLATE_NOOP("kerrigan", "Invalid minimum number of spork signers specified with -minsporkkeys"),
QT_TRANSLATE_NOOP("kerrigan", "Invalid netmask specified in -whitelist: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Invalid port specified in %s: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Invalid script detected."),
QT_TRANSLATE_NOOP("kerrigan", "Invalid spork address specified with -sporkaddr"),
QT_TRANSLATE_NOOP("kerrigan", "Last queue was created too recently."),
QT_TRANSLATE_NOOP("kerrigan", "Last successful action was too recent."),
QT_TRANSLATE_NOOP("kerrigan", "Listening for incoming connections failed (listen returned error %s)"),
QT_TRANSLATE_NOOP("kerrigan", "Loading P2P addresses…"),
QT_TRANSLATE_NOOP("kerrigan", "Loading banlist…"),
QT_TRANSLATE_NOOP("kerrigan", "Loading block index…"),
QT_TRANSLATE_NOOP("kerrigan", "Loading wallet…"),
QT_TRANSLATE_NOOP("kerrigan", "Lock is already in place."),
QT_TRANSLATE_NOOP("kerrigan", "Masternode queue is full."),
QT_TRANSLATE_NOOP("kerrigan", "Masternode:"),
QT_TRANSLATE_NOOP("kerrigan", "Missing input transaction information."),
QT_TRANSLATE_NOOP("kerrigan", "Missing solving data for estimating transaction size"),
QT_TRANSLATE_NOOP("kerrigan", "Need to specify a port with -whitebind: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "No Masternodes detected."),
QT_TRANSLATE_NOOP("kerrigan", "No addresses available"),
QT_TRANSLATE_NOOP("kerrigan", "No compatible Masternode found."),
QT_TRANSLATE_NOOP("kerrigan", "No errors detected."),
QT_TRANSLATE_NOOP("kerrigan", "No host specified"),
QT_TRANSLATE_NOOP("kerrigan", "No host specified, malformed URL"),
QT_TRANSLATE_NOOP("kerrigan", "No text before the scheme delimiter, malformed URL"),
QT_TRANSLATE_NOOP("kerrigan", "Not compatible with existing transactions."),
QT_TRANSLATE_NOOP("kerrigan", "Not enough file descriptors available."),
QT_TRANSLATE_NOOP("kerrigan", "Not enough funds to mix."),
QT_TRANSLATE_NOOP("kerrigan", "Not in the Masternode list."),
QT_TRANSLATE_NOOP("kerrigan", "Port must be between %d and %d, supplied %d"),
QT_TRANSLATE_NOOP("kerrigan", "Prune cannot be configured with a negative value."),
QT_TRANSLATE_NOOP("kerrigan", "Prune mode is incompatible with -disablegovernance=false."),
QT_TRANSLATE_NOOP("kerrigan", "Prune mode is incompatible with -txindex."),
QT_TRANSLATE_NOOP("kerrigan", "Pruning blockstore…"),
QT_TRANSLATE_NOOP("kerrigan", "Reducing -maxconnections from %d to %d, because of system limitations."),
QT_TRANSLATE_NOOP("kerrigan", "Replaying blocks…"),
QT_TRANSLATE_NOOP("kerrigan", "Rescanning…"),
QT_TRANSLATE_NOOP("kerrigan", "SQLiteDatabase: Failed to execute statement to verify database: %s"),
QT_TRANSLATE_NOOP("kerrigan", "SQLiteDatabase: Failed to prepare statement to verify database: %s"),
QT_TRANSLATE_NOOP("kerrigan", "SQLiteDatabase: Failed to read database verification error: %s"),
QT_TRANSLATE_NOOP("kerrigan", "SQLiteDatabase: Unexpected application id. Expected %u, got %u"),
QT_TRANSLATE_NOOP("kerrigan", "Section [%s] is not recognized."),
QT_TRANSLATE_NOOP("kerrigan", "Session not complete!"),
QT_TRANSLATE_NOOP("kerrigan", "Session timed out."),
QT_TRANSLATE_NOOP("kerrigan", "Signing transaction failed"),
QT_TRANSLATE_NOOP("kerrigan", "Socket not initialized, cannot send message"),
QT_TRANSLATE_NOOP("kerrigan", "Specified -walletdir \"%s\" does not exist"),
QT_TRANSLATE_NOOP("kerrigan", "Specified -walletdir \"%s\" is a relative path"),
QT_TRANSLATE_NOOP("kerrigan", "Specified -walletdir \"%s\" is not a directory"),
QT_TRANSLATE_NOOP("kerrigan", "Specified blocks directory \"%s\" does not exist."),
QT_TRANSLATE_NOOP("kerrigan", "Starting network threads…"),
QT_TRANSLATE_NOOP("kerrigan", "Submitted to masternode, waiting in queue %s"),
QT_TRANSLATE_NOOP("kerrigan", "Synchronization finished"),
QT_TRANSLATE_NOOP("kerrigan", "Synchronizing blockchain…"),
QT_TRANSLATE_NOOP("kerrigan", "Synchronizing governance objects…"),
QT_TRANSLATE_NOOP("kerrigan", "The source code is available from %s."),
QT_TRANSLATE_NOOP("kerrigan", "The specified config file %s does not exist"),
QT_TRANSLATE_NOOP("kerrigan", "The transaction amount is too small to pay the fee"),
QT_TRANSLATE_NOOP("kerrigan", "The wallet will avoid paying less than the minimum relay fee."),
QT_TRANSLATE_NOOP("kerrigan", "This is expected because you are running a pruned node."),
QT_TRANSLATE_NOOP("kerrigan", "This is experimental software."),
QT_TRANSLATE_NOOP("kerrigan", "This is the minimum transaction fee you pay on every transaction."),
QT_TRANSLATE_NOOP("kerrigan", "This is the transaction fee you will pay if you send a transaction."),
QT_TRANSLATE_NOOP("kerrigan", "Topping up keypool…"),
QT_TRANSLATE_NOOP("kerrigan", "Transaction amount too small"),
QT_TRANSLATE_NOOP("kerrigan", "Transaction amounts must not be negative"),
QT_TRANSLATE_NOOP("kerrigan", "Transaction change output index out of range"),
QT_TRANSLATE_NOOP("kerrigan", "Transaction created successfully."),
QT_TRANSLATE_NOOP("kerrigan", "Transaction fees are too high."),
QT_TRANSLATE_NOOP("kerrigan", "Transaction has too long of a mempool chain"),
QT_TRANSLATE_NOOP("kerrigan", "Transaction must have at least one recipient"),
QT_TRANSLATE_NOOP("kerrigan", "Transaction needs a change address, but we can't generate it."),
QT_TRANSLATE_NOOP("kerrigan", "Transaction not valid."),
QT_TRANSLATE_NOOP("kerrigan", "Transaction too large"),
QT_TRANSLATE_NOOP("kerrigan", "Trying to connect…"),
QT_TRANSLATE_NOOP("kerrigan", "Unable to bind to %s on this computer (bind returned error %s)"),
QT_TRANSLATE_NOOP("kerrigan", "Unable to bind to %s on this computer. %s is probably already running."),
QT_TRANSLATE_NOOP("kerrigan", "Unable to create the PID file '%s': %s"),
QT_TRANSLATE_NOOP("kerrigan", "Unable to find UTXO for external input"),
QT_TRANSLATE_NOOP("kerrigan", "Unable to generate initial keys"),
QT_TRANSLATE_NOOP("kerrigan", "Unable to locate enough mixed funds for this transaction."),
QT_TRANSLATE_NOOP("kerrigan", "Unable to locate enough non-denominated funds for this transaction."),
QT_TRANSLATE_NOOP("kerrigan", "Unable to lookup host %s"),
QT_TRANSLATE_NOOP("kerrigan", "Unable to open %s for writing"),
QT_TRANSLATE_NOOP("kerrigan", "Unable to parse -maxuploadtarget: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Unable to send message to %s (::sendto() returned error %s)"),
QT_TRANSLATE_NOOP("kerrigan", "Unable to sign spork message, wrong key?"),
QT_TRANSLATE_NOOP("kerrigan", "Unable to start HTTP server. See debug log for details."),
QT_TRANSLATE_NOOP("kerrigan", "Unknown -blockfilterindex value %s."),
QT_TRANSLATE_NOOP("kerrigan", "Unknown network specified in -onlynet: '%s'"),
QT_TRANSLATE_NOOP("kerrigan", "Unknown new rules activated (versionbit %i)"),
QT_TRANSLATE_NOOP("kerrigan", "Unknown response."),
QT_TRANSLATE_NOOP("kerrigan", "Unknown state: id = %u"),
QT_TRANSLATE_NOOP("kerrigan", "Unsupported URL scheme, must begin with udp://"),
QT_TRANSLATE_NOOP("kerrigan", "Unsupported global logging level -loglevel=%s. Valid values: %s."),
QT_TRANSLATE_NOOP("kerrigan", "Unsupported logging category %s=%s."),
QT_TRANSLATE_NOOP("kerrigan", "User Agent comment (%s) contains unsafe characters."),
QT_TRANSLATE_NOOP("kerrigan", "Verifying blocks…"),
QT_TRANSLATE_NOOP("kerrigan", "Verifying wallet(s)…"),
QT_TRANSLATE_NOOP("kerrigan", "Very low number of keys left: %d"),
QT_TRANSLATE_NOOP("kerrigan", "Wallet is locked."),
QT_TRANSLATE_NOOP("kerrigan", "Wallet needed to be rewritten: restart %s to complete"),
QT_TRANSLATE_NOOP("kerrigan", "Warning: can't use %s and %s together, will prefer %s"),
QT_TRANSLATE_NOOP("kerrigan", "Warning: incorrect parameter %s, path must exist! Using default path."),
QT_TRANSLATE_NOOP("kerrigan", "Wasn't able to create wallet backup folder %s!"),
QT_TRANSLATE_NOOP("kerrigan", "Will retry…"),
QT_TRANSLATE_NOOP("kerrigan", "Wiping wallet transactions…"),
QT_TRANSLATE_NOOP("kerrigan", "You are starting with governance validation disabled."),
QT_TRANSLATE_NOOP("kerrigan", "You can not disable governance validation on a masternode."),
QT_TRANSLATE_NOOP("kerrigan", "You can not start a masternode with wallet enabled."),
QT_TRANSLATE_NOOP("kerrigan", "You need to rebuild the database using -reindex to enable -addressindex"),
QT_TRANSLATE_NOOP("kerrigan", "You need to rebuild the database using -reindex to enable -spentindex"),
QT_TRANSLATE_NOOP("kerrigan", "Your entries added successfully."),
QT_TRANSLATE_NOOP("kerrigan", "see debug.log for details."),
};
